name: 莞工防控疫情打卡
on:
  push:
    branches:
      - main
  schedule:
    - cron: '3 8,16,20 * * *'
  workflow_dispatch:
  watch:
    types: started
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Report
        run: python Auto_Report.py -U ${{ secrets.USERNAME }} -P ${{ secrets.PASSWORD }} ${{ secrets.LOCATIONS }}

